Repository kouprlabs/voltaserve, pull requests merged in 2024-09, with the labels that each got.

#296 Initial version of Cloud Console API
  .env
  .github/workflows/build-console.yml
  .github/workflows/check-on-pr-console.yml
  console/.dockerignore
  console/Dockerfile
  console/api/.env
  console/api/__init__.py
  console/api/database/__init__.py
  console/api/database/generic.py
  console/api/database/group.py
  console/api/database/index.py
  console/api/database/invitation.py
  console/api/database/organization.py
  console/api/database/overview.py
  console/api/database/snapshot.py
  console/api/database/task.py
  console/api/database/user.py
  console/api/database/workspace.py
  console/api/dependencies/__init__.py
  console/api/dependencies/database.py
  console/api/dependencies/jwt.py
  console/api/dependencies/meilisearch.py
  console/api/dependencies/settings.py
  console/api/dependencies/utils.py
  console/api/errors/__init__.py
  console/api/errors/api_errors.py
  console/api/errors/database_errors.py
  console/api/errors/error_codes.py
  console/api/log.py
  console/api/main.py
  console/api/models/__init__.py
  console/api/models/generic.py
  console/api/models/group.py
  console/api/models/grouppermission.py
  console/api/models/groupuser.py
  console/api/models/index.py
  console/api/models/invitation.py
  console/api/models/organization.py
  console/api/models/overview.py
  console/api/models/snapshot.py
  console/api/models/snapshotfile.py
  console/api/models/task.py
  console/api/models/token.py
  console/api/models/user.py
  console/api/models/userpermission.py
  console/api/models/workspace.py
  console/api/routers/__init__.py
  console/api/routers/group.py
  console/api/routers/index.py
  console/api/routers/invitation.py
  console/api/routers/organization.py
  console/api/routers/overview.py
  console/api/routers/snapshot.py
  console/api/routers/user.py
  console/api/routers/workspace.py
  console/api/uvi.py
  console/poetry.lock
  console/pyproject.toml
  docker-compose.yml
Labels: feature

#302 feat: cloud console api adjustment
  console/api/.env
  console/api/database/index.py
  console/api/main.py
  console/api/models/index.py
  console/api/routers/index.py
  console/api/routers/overview.py
Labels: refactoring

#309 fix: missing SECURITY_JWT_SIGNING_KEY
  console/api/.env
Labels: bug

#308 fix: added W503 line break before binary operator ignore
  .github/workflows/check-on-pr-console.yml
Labels: bug

#321 chore: IDEA run
  .gitignore
  .run/all (go).run.xml
  .run/all (node).run.xml
  .run/all (python).run.xml
  .run/all (rust).run.xml
  .run/api.run.xml
  .run/console.run.xml
  .run/conversion.run.xml
  .run/idp.run.xml
  .run/language.run.xml
  .run/migrations.run.xml
  .run/mosaic.run.xml
  .run/ui.run.xml
  .run/webdav.run.xml
Labels: Title needs formatting!

#330 ci(workflow): added misc to pr-title-checker
  .github/pr-title-checker-config.json
Labels: enhancement

#331 ci(workflow): minor improvements to pipelines
  .github/workflows/build-api.yml
  .github/workflows/build-console.yml
  .github/workflows/build-conversion.yml
  .github/workflows/build-idp.yml
  .github/workflows/build-language.yml
  .github/workflows/build-migrations.yml
  .github/workflows/build-mosaic.yml
  .github/workflows/build-ui.yml
  .github/workflows/build-webdav.yml
  .github/workflows/check-on-pr-api.yml
  .github/workflows/check-on-pr-console.yml
  .github/workflows/check-on-pr-conversion.yml
  .github/workflows/check-on-pr-idp.yml
  .github/workflows/check-on-pr-language.yml
  .github/workflows/check-on-pr-migrations.yml
  .github/workflows/check-on-pr-mosaic.yml
  .github/workflows/check-on-pr-ui.yml
  .github/workflows/check-on-pr-webdav.yml
Labels: enhancement

#337 feat(console): add cache delete on patch
  console/api/.env
  console/api/database/organization.py
  console/api/dependencies/__init__.py
  console/api/dependencies/redis.py
  console/api/dependencies/settings.py
  console/api/routers/group.py
  console/api/routers/organization.py
  console/api/routers/workspace.py
  console/poetry.lock
  console/pyproject.toml
Labels: enhancement
